### ISSUE TITLE
MacOS compile failed

### ISSUE THREAD

**Issue by XiaLiChao82** [kirillochnev/mustache#58]
The code failed to compile on my Mac because the file "malloc.h" could not be found on the mac and needed to be replaced with "sys/malloc.h". Second, the example program crashed because aligned_alloc returned a null pointer. align needs to be set to 8 or greater to ensure that the pointer is not null

**Comment by kirillochnev** [comment]
Thank you for your feedback. I'll try to find MacOS to fix your issue as soos as possible.
P.S. If you has fix, feel free to create pull request.

**Comment by XiaLiChao82** [comment]
Okey, I've created my pull request
